site_name: Ergänzungen zum C# Buch

nav:
  - Übersicht: index.md
  # - 1 Einführung: content/1.md
  - 2.4 Verzweigungen mit if und else: content/2.md
  - 2.6 Verzweigungen und Steuerelemente: content/2_6.md
  # - 3 Fehlerbehandlung: content/3.md
  # - 4 Erweiterte Grundlagen: content/4.md
  # - 5 Objektorientierte Programmierung: content/5.md
  # - 6 Wichtige Klassen in .NET: content/6.md
  # - 7 Weitere Elemente eines Windows-Programms: content/7.md
  # - 8 Datenbankanwendungen: content/8.md
  # - 9 Zeichnen mit GDI+: content/9.md

theme:
  name: material
  palette:
    primary: amber
    accent: indigo
  features:
    - navigation.tracking
    - navigation.path
    - navigation.top
    - navigation.footer
    - toc.follow
    - toc.integrate
    - content.code.copy
    - content.code.annotate

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - attr_list
  - md_in_html

extra_css:
  - stylesheets/grid.css

plugins:
    - search
    - macros

watch:
  - tasks

copyright: Copyright &copy; 2025 Qualidy GmbH