title: Eine Checkbox
question: |
  Erstelle eine Checkbox mit den Text "Großschrift".
  Erstelle ein Label mit einem Text.

  Finde heraus, wie du die Schriftgröße des Textes ändern kannst.

  Sorge dafür, dass wenn du die Checkbox aktivierst,
  die Schrift im Label vergrößert wird.
solution: |
  ```csharp
  namespace DeineApp
  {
      public partial class Form1 : Form
      {
          private const Font normalFont;
          private const Font largeFont;

          public Form1()
          {
              InitializeComponent();
          }

          private void ChkGrossschrift_CheckedChanged(object sender, EventArgs e)
          {
              LblText.Font = ChkGrossschrift.Checked ? largeFont : normalFont;
          }
      }
  }

  ```
